# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=20)),
                ('logo', models.FileField(upload_to='albumlogos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='files/')),
                ('name', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=10)),
                ('size', models.BigIntegerField(blank=True, default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=10)),
                ('size', models.BigIntegerField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('song', models.FileField(upload_to='song/')),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('size', models.BigIntegerField(blank=True, default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Comedy', 'Comedy'), ('Educational', 'Educational'), ('Horror', 'Horror'), ('others', 'others')], max_length=10)),
                ('video', models.FileField(upload_to='videos/')),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('size', models.BigIntegerField(blank=True, default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='653', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
