# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170902_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Musical genres', 'Musical genres'), ('Jazz', 'Jazz'), ('Folk', 'Folk'), ('Hardcore', 'Hardcore'), ('Blues', 'Blues'), ('Rapping', 'Rapping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='583', max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Educational', 'Educational'), ('Horror', 'Horror'), ('others', 'others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videos',
            name='extension',
            field=models.CharField(blank=True, default='mp4', max_length=10),
        ),
        migrations.AlterField(
            model_name='videos',
            name='size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
