# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170906_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='826', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Educational', 'Educational'), ('Horror', 'Horror'), ('Song', 'Song'), ('Movie', 'Movie'), ('others', 'others')], max_length=20),
        ),
    ]
