# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170906_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='652', max_length=100),
        ),
    ]
