# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0012_auto_20171002_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_to',
            field=models.ForeignKey(blank=None, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='979', max_length=100),
        ),
    ]
