# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20171002_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='231', max_length=100),
        ),
    ]
