# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20171002_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='246', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
