# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20171031_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
